### ISSUE TITLE
nextcloud-reloaded: acme.sh is not renewing

### ISSUE THREAD

**Issue by tasmo** [ReinerNippes/nextcloud13#129]
The playbook does not or cannot check if the certificates have to be renewed or not.

On my server I did take a look one day before the end of the validation period of the Letsencrypt cert. It should renew at least 10 days before.

How can I debug this to give more information?

**Comment by ReinerNippes** [comment]
The certificate renewal is not handled by the playbook itself. 
acme.sh should create a cronjob for root to do this. 
You may look if `sudo crontab -e`  will show a line like `"/opt/acme/sh"/acme.sh --cron --home "/opt/acme/sh" --config-home "/opt/acme/sh/conf"` 
You may run this command and check the output.
