### ISSUE TITLE
Task [prep_nginx: throwing No package matching 'python-pip' is available

### ISSUE THREAD

**Issue by LAazsx** [ReinerNippes/nextcloud13#134]
Hi, 

First time using Ansible here and I'm running Ubuntu 20.04. 

Running nextcloud.yml fails when it reaches [prep_nginx: install needed packages]. I've verified `pip3 --version` returns 
`pip 22.0.3 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)`

Any thoughts?

**Comment by LAazsx** [comment]
I was able to fix the issue by modifying `/nextcloud/roles/prep_nginx/Ubuntu.yml` and under ``install needed packages`, change `python-pip` to `python3-pip`

**Comment by ReinerNippes** [comment]
Better have a look at the nextcloud-reloaded branch. It should be fixed there.
But beware. They are not compatible. That's why I didn't merge them.

**Comment by LAazsx** [comment]
Yeah, I'm already on nextcloud_reloaded branch when I noticed that 20.04 is not yet supported on this one.
