### ISSUE TITLE
Let's Encrypt error

### ISSUE THREAD

**Issue by fpernice518** [ReinerNippes/nextcloud13#6]
I'm trying use your script, but it seems to fail at Let's Encrypt for me. I believe my ISP blocks port 80, so right now I'm re-routing port 80 on my server to port 81 (and 443 to 444). That seemed to work for the snap install I did prior to using your script (I've since done a clean install of Ubuntu and tried with your script since I could not get Let's Encrypt working with snap). 

I'm using afraid.org /FreeDNS as my DDNS. I can post my inventory file later when I get home from work.
Thanks for any help you can provide!

Error Message (I've changed the subdomain and email address for my privacy):

`fatal: [localhost]: FAILED! => {"changed": true, "cmd": "certbot --authenticator        webroot --webroot-path=/var/www/letsencrypt --installer nginx --email misc@myemail.com --non-interactive --domain mysubdomain.chickenkiller.com --agree-tos "       , "delta": "0:00:14.898765", "end": "2018-08-01 02:49:29.787350", "msg": "non-ze       ro return code", "rc": 1, "start": "2018-08-01 02:49:14.888585", "stderr": "Savi       ng debug log to /var/log/letsencrypt/letsencrypt.log\nPlugins selected: Authenti       cator webroot, Installer nginx\nObtaining a new certificate\nPerforming the foll       owing challenges:\nhttp-01 challenge for mysubdomain.chickenkiller.com\nUsing the w       ebroot path /var/www/letsencrypt for all unmatched domains.\nWaiting for verific       ation...\nCleaning up challenges\nFailed authorization procedure. mysubdomain.chick       enkiller.com (http-01): urn:ietf:params:acme:error:connection :: The server coul       d not connect to the client to verify the domain :: Fetching http://mysubdomain.chi       ckenkiller.com/.well-known/acme-challenge/CVIZ86a9nNnrIsv_8tVyHTFKBa4CxEezqTqBW3       M9PLs: Timeout during connect (likely firewall problem)", "stderr_lines": ["Savi       ng debug log to /var/log/letsencrypt/letsencrypt.log", "Plugins selected: Authen       ticator webroot, Installer nginx", "Obtaining a new certificate", "Performing th       e following challenges:", "http-01 challenge for mysubdomain.chickenkiller.com", "U       sing the webroot path /var/www/letsencrypt for all unmatched domains.", "Waiting        for verification...", "Cleaning up challenges", "Failed authorization procedure       . mysubdomain.chickenkiller.com (http-01): urn:ietf:params:acme:error:connection ::        The server could not connect to the client to verify the domain :: Fetching htt       p://mysubdomain.chickenkiller.com/.well-known/acme-challenge/CVIZ86a9nNnrIsv_8tVyHT       FKBa4CxEezqTqBW3M9PLs: Timeout during connect (likely firewall problem)"], "stdo       ut": "IMPORTANT NOTES:\n - The following errors were reported by the server:\n\n          Domain: mysubdomain.chickenkiller.com\n   Type:   connection\n   Detail: Fetchin       g\n   http://mysubdomain.chickenkiller.com/.well-known/acme-challenge/CVIZ86a9nNnrI       sv_8tVyHTFKBa4CxEezqTqBW3M9PLs:\n   Timeout during connect (likely firewall prob       lem)\n\n   To fix these errors, please make sure that your domain name was\n   e       ntered correctly and the DNS A/AAAA record(s) for that domain\n   contain(s) the        right IP address. Additionally, please check that\n   your computer has a publi       cly routable IP address and that no\n   firewalls are preventing the server from        communicating with the\n   client. If you're using the webroot plugin, you shou       ld also verify\n   that you are serving files from the webroot path you provided       .\n - Your account credentials have been saved in your Certbot\n   configuration        directory at /etc/letsencrypt. You should make a\n   secure backup of this fold       er now. This configuration directory will\n   also contain certificates and priv       ate keys obtained by Certbot so\n   making regular backups of this folder is ide       al.", "stdout_lines": ["IMPORTANT NOTES:", " - The following errors were reporte       d by the server:", "", "   Domain: mysubdomain.chickenkiller.com", "   Type:   conn       ection", "   Detail: Fetching", "   http://mysubdomain.chickenkiller.com/.well-know       n/acme-challenge/CVIZ86a9nNnrIsv_8tVyHTFKBa4CxEezqTqBW3M9PLs:", "   Timeout duri       ng connect (likely firewall problem)", "", "   To fix these errors, please make        sure that your domain name was", "   entered correctly and the DNS A/AAAA record       (s) for that domain", "   contain(s) the right IP address. Additionally, please        check that", "   your computer has a publicly routable IP address and that no",        "   firewalls are preventing the server from communicating with the", "   client       . If you're using the webroot plugin, you should also verify", "   that you are        serving files from the webroot path you provided.", " - Your account credentials        have been saved in your Certbot", "   configuration directory at /etc/letsencry       pt. You should make a", "   secure backup of this folder now. This configuration        directory will", "   also contain certificates and private keys obtained by Cer       tbot so", "   making regular backups of this folder is ideal."]}`

**Comment by ReinerNippes** [comment]
well. the certbot faq say's port 80 has to be open.
https://certbot.eff.org/faq/#can-i-issue-a-certificate-if-my-webserver-doesn-t-listen-on-port-80

but.
to finish installation setup selfsigned certificate for your domain. that should finish the the installation of nextcloud and you can use it.

maybe the following plugin for certbot can help you getting a letsencrypt certificate.
https://github.com/EnigmaBridge/certbot-external-auth
https://dan.enigmabridge.com/powering-simplicity-of-certbot-and-letsencrypt-domain-verification/

once the certificates are in place you can change the inventory again to letsencrypt end rerun the playbook. it will setup everything correct but skip the "certbot" command. 

another idea would be to get a cheap "mini server" on the internet and setup a reverse proxy to forward port 80 to 81 and 443 to 444 before your isp's firewall. 

https://lowendbox.com/ you find there server starting $12/y. since it's just a reverse proxy probably the power of such a machine will be ok.
